<?php

namespace tests\app\assets;

use yii\web\AssetBundle;

/**
 * Configuration for `backend` client script files
 * @since 4.0
 */
class AppAsset extends AssetBundle
{
    public $sourcePath = '@app/assets/web';

    public $css = [
        'css/app.css',
    ];

    public function init()
    {
        $this->depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap4\BootstrapAsset',
            'bedezign\yii2\audit\web\JSLoggingAsset',
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }


}
